### PR TITLE
feat: add flyway migrator

### LINKED ISSUE #14: Setting up flyway migrator for db
https://www.baeldung.com/database-migrations-with-flyway

### PR DESCRIPTION
**Pull request by mpfan**
This pr adds a flyway migrator to the project. The purpose is to be able to manage database changes in a consistent manner.

Note to all reviewer: once a migration file has been merged to main that file should not be modified anymore. Further db changes should be done in new migration files.

Closes #14

### CODE REVIEW

**Comment by mpfan** [comment]
Need to configure a test and a prod postgres db on heroku first.

**Comment by mpfan** [comment]
The test db has been setup. https://data.heroku.com/datastores/67a1e7df-f5fc-4fea-8088-060b2110faf7#

**Review by Weebian — APPROVED** [review]
looks good

**Comment by mpfan** [comment]
image
You need these env vars to run.

**Pull request merged**
